channels:
  - nicolasradomski
  - conda-forge
  - defaults

package:
  name: genomicbasedclassification
  version: "1.2.0"

source:
  path: .

build:
  number: 0
  script: |
    mkdir -p "$PREFIX/bin"
    cp "$SRC_DIR/GenomicBasedClassification.py" "$PREFIX/bin/GenomicBasedClassification.py"
    echo '#!/bin/bash' > "$PREFIX/bin/genomicbasedclassification"
    echo 'python "$CONDA_PREFIX/bin/GenomicBasedClassification.py" "$@"' >> "$PREFIX/bin/genomicbasedclassification"
    chmod +x "$PREFIX/bin/genomicbasedclassification"

requirements:
  host:
    - python=3.12
    - pip
  run:
    - python=3.12
    - pandas=2.2.2
    - imbalanced-learn=0.13.0
    - scikit-learn=1.5.2
    - xgboost=2.1.3
    - numpy=1.26.4
    - joblib==1.5.1
    - tqdm=4.67.1
    - tqdm-joblib=0.0.4
    - catboost==1.2.8

about:
  home: "https://github.com/Nicolas-Radomski/GenomicBasedClassification"
  summary: "Script performing classification-based modeling or prediction from genomic data"
  license: "GPL-3.0"

extra:
  recipe-maintainers:
    - Nicolas-Radomski

test:
  commands:
    - python -c "import pandas, imblearn, sklearn, xgboost, numpy, joblib, tqdm, tqdm_joblib; print('Test successful')"
    - python "$CONDA_PREFIX/bin/GenomicBasedClassification.py" --help
    - genomicbasedclassification --help
